### PR TITLE
Add support for checking the fingerprint of self-signed SSL certs

### PR DESCRIPTION
**Pull request by sinbad**
Discussed with @novabyte on Gitter, sounds like this could be useful. 

I wanted to have some checking of SSL certs even though I was using a self-signed certificate, so I've added the ability to provide a list of cert fingerprints that are considered acceptable. Example usage:

```csharp
        var client = new NClient.Builder(sb.ToString())
            .Host("your.host.com")
            .Port(443)
            .SSL(true)
            .SSLAcceptAllCertificates(false)
            .SSLValidKeyFingerprints(new string[] { "9E10ACEB4DD13F0FD3E187C3CBC270605EA65031" })
            .Build();
```
It defaults to the previous behaviour to accept all certificates so as not to break anything, although I really think the default should be the opposite at some point to encourage better security.

Hope it's useful!

### CODE REVIEW

**Comment by MarcusRiemer** [comment]
Is there any ETA for this? Or any reason why this shouldn't be merged?

**Comment by novabyte** [comment]
@MarcusRiemer Since the launch of the new client I've separated out this work into a separate commit which will be completed tomorrow. And incorporated as part of the release. 😄

**Comment by novabyte** [comment]
This was added in the 2.1.0 release.

**Comment by StrixSC** [comment]
Hello,

I cannot seem to find the change added anywhere. Has this been removed since then with newer Nakama patches? Thank you

**Comment by brandondines** [comment]
also looking for this for local testing, is there a supported way of doing this?

**Pull request closed without merging**
