### PR TITLE
Support the unity package manager

### LINKED ISSUE #91: Migrate to Unity package manager
##### Describe the problem

To share systems between games, it is becoming common to create Unity packages that can specify their own external dependencies. Then it's a simple matter of adding the new package to each game's package manifest.

Updating the Nakama SDK in 10 of our games requires us to copy code 10 times, and it's unclear what version of the package each game is even using.

##### Describe the solution you'd like

Ideally, the Nakama SDK would be a Unity package now that Unity natively supports package management. This would allow us to do something like:

```
{
  "dependencies": {
    "com.heroiclabs.nakama": "git+https://github.com/heroiclabs/nakama.git"
  },
  "lock": {
    "com.heroiclabs.nakama": {
      "hash": "some-git-hash",
      "revision": "HEAD"
    }
  }
}
```

The lock is optional, and would allow us to specify experimental branches or specific revisions in the case there is a breaking bug.

### PR DESCRIPTION
**Pull request by lugehorsam**
As rightfully requested by @thegoldenmule

This mostly involved shuffling files around into a particular folder structure and creating assembly definitions for the Editor and Runtime bundles of our scripts.

Here's what it looks like in the package manager:

Screen Shot 2020-07-28 at 9 20 48 PM

Closes #91

### CODE REVIEW

**Comment by lugehorsam** [comment]
I was looking for ways for the "In Development" label to not show up. As far as I can tell, unless the user downloads our package in UPM via the Asset Store, we will have that label. So that is a bit annoying but I am not sure if there's anything we can do about it. Obviously we'll still publish to the Asset Store so it'll go away if users use that flow rather than a git url.

**Comment by novabyte** [comment]
@lugehorsam Awesome. I have only a small follow up request. We should document the steps to add this client with UPM to the README and the client guide page on the docs.

**Comment by thegoldenmule** [comment]
@lugehorsam This is awesome!

**Comment by lugehorsam** [comment]
@novabyte There are a few different ways of doing it which is why I kept it vague. But perhaps I document the asset store and git url examples since I'd imagine those are the two most common ways of doing it.

**Comment by lugehorsam** [comment]
@novabyte Done. One of the new methods is to download a .tar from the releases page and import it into UPM. However, that will be an unsupported README.md instruction until we make a new release. Thoughts on making a new release?

**Comment by novabyte** [comment]
@lugehorsam We should cut a new release but I want to bring in the changes to the .NET client that @thegoldenmule contributed that resolves an issue with encoding JSON numeric primitives.

**Comment by lugehorsam** [comment]
Added 9498008 because Unity complains if you import a package that doesn't have `.meta` files.

**Comment by novabyte** [comment]
@lugehorsam I think we can merge this into master. The [latest](https://github.com/heroiclabs/nakama-dotnet/releases/v2.5.0) .NET client release is out and we can prepare for a release of the Unity client.

**Pull request merged**
