### PR TITLE
Enable finer control over what thread and when callbacks are executed on.

### PR DESCRIPTION
**Pull request by JoshuaStrunk**
There are many reasons to enable developers to choose when their callbacks are handled. The most obvious being methods in the UnityEngine API must be called from the main thread. I am not claiming this is the best way to handle this simply putting forward a starting point for discussion.

### CODE REVIEW

**Comment by zyro** [comment]
@JoshuaStrunk Thanks for the PR! I agree this looks like a great starting point. Here are some points I want to bring up to get the discussion going.

I'm not familiar with any way to limit the size of the `Queue`. Is it acceptable to allow it to grow unbounded if the application doesn't process events for some time, or is too slow and callbacks accumulate faster than they're consumed?

Does the `while` loop inside `ProcessCallbacks()` potentially prevent controlling the maximum execution time of any given call to the process function? Would it be better to leave this to the application and instead each call to `ProcessCallbacks()` processes exactly one item?

If there are any special considerations or guidelines you recommend we should put together some minimal code examples or snippets for the docs, any help there would be great as well.

**Comment by JoshuaStrunk** [comment]
I actually had thought about not looping in `ProcessCallbacks()`. 
I had not considered the unbounded growth of the queue though a [`Queue.Count` is performed in constant time.](https://msdn.microsoft.com/en-us/library/fy0wwyz4.aspx) so could hard code a limit in the enqueuing logic. My stance is, if the Client can not keep up with the `callbackQueue`, then something else going wrong and perhaps the Client should even be disconnected. Where that callback limit should be I am not sure.

**Comment by prodigga** [comment]
I would like to chime in here and say that, whatever the solution, I feel like it should be something that "sits on top" of whatever nakama client is doing. We've been working with nakama for 2 weeks now, and we've started putting together our own "framework" that sits above all the nakama code. The fact that Nakama Unity is so minimalistic means that I have a lot of flexibility.

I've implemented my own "match event system". My event system hooks into OnMatchData, and it is in charge of deserializing incoming messages by looking at the OpCode and deciding what to do with it. Then it adds the deserialized event data to a queue of event data's, and invokes the correct callbacks based on the event data type on the next Update. (So that subscribers to those events get notified only the main thread).

Objects can subscribe to different event data types and get a callback when that data type is received by my event system.

To subscribe to a specific event:

```MatchEvents.Subscribe<PositionalUpdate>(OnPositionalUpdate);
...

private void OnPositionalUpdate (PositionalUpdate eventData) 
{ ....}```

And to send the event:

```var posData = new PositionalUpdate (transform.position, transform.rotation);
MatchEvents.Send(posData);```

I've written all this code to hide away all the serialisation/deserializion logic, it is all handled by my MatchEvents class and it works really well. 

Because the OnMatchData callback happens in a background thread, there is also the added bonus of my deserializion code running in the background and not holding up my main thread.

All of this was possible because nakama is fairly low level. It lets me add my own framework/game specific logic on top.

Now, I do understand that this might be a lot of stuff for a new user to have to worry about. They just want to jump in and try it out.

So for this reason I suggest we create a seperate repo with Nakama Unity samples. We can provide some sample code to show people how they could go about working with Nakama. (Explain how OnMatchData isn't on the main thread, etc). I think it would be a shame to loose a this flexibility to make the framework more accessible, when a few simple example scripts could be enough to get people started.

**Comment by novabyte** [comment]
This is addressed in https://github.com/heroiclabs/nakama-unity/pull/17 but I'd like some feedback before it's merged.

**Pull request closed without merging**
